[build.environment]
NODE_VERSION = "20.12.2" # - latest NODE version
NPM_VERSION = "10.5.2"   # - latest NPM version
YARN_VERSION = "1.22.22" # - latest YARN version

[dev]
command = "npm run develop"
publish = "public"
