[build.environment]
  NODE_VERSION = "20.8.1" # - latest NODE version
  # NODE_VERSION = "17.9.0" # - stable NODE 17+
  # NODE_VERSION = "18.11.0" # - stable NODE 18+
  NPM_VERSION = "10.2.0" # - latest NPM
  # NPM_VERSION = "8.13.2" # - stable NPM
  YARN_VERSION = "1.22.19" # - latest YARN



[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
  
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' frame-ancestors app.contentful.com"
