[build.environment]
  NODE_VERSION = "20.11.0" # - latest NODE version
  NPM_VERSION = "10.4.0" # - latest NPM version
  YARN_VERSION = "1.22.21" # - latest YARN version

[dev]
  command = "npm run develop" 
  publish = "public"